const CATEGORIES={care:"介護・医療",welfare:"福祉用具",local:"宮城・仙台",general:"国内・経済"};
let allNews=[];let current="care";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmtDate=s=>{if(!s)return"日付記載なし";const d=new Date(s);return Number.isNaN(d.getTime())?s:new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric"}).format(d)};
function card(item,important=false){const n=document.getElementById("card-template").content.firstElementChild.cloneNode(true);n.dataset.category=item.category;n.classList.toggle("important",important);n.querySelector(".tag").textContent=CATEGORIES[item.category]||"新着";n.querySelector(".status").textContent=item.status||"公式発表";n.querySelector("h3").textContent=item.title;n.querySelector(".summary").textContent=item.summary;n.querySelector(".source-name").textContent=item.source;n.querySelector("time").textContent=fmtDate(item.published);n.querySelector(".card-button").addEventListener("click",()=>showDetail(item));return n}
function showDetail(x){document.getElementById("detail").innerHTML=`<span class="detail-tag">${esc(CATEGORIES[x.category]||"新着")}</span><h2 class="detail-title" id="detail-title">${esc(x.title)}</h2><p class="detail-summary">${esc(x.detail||x.summary)}</p><div class="fact-box"><strong>${esc(x.status||"公式発表")}</strong>${esc(x.fact_note||"掲載元が公表している範囲だけを表示しています。")}</div><div class="source-box"><b>出典：</b>${esc(x.source)}<br><b>公表日：</b>${esc(fmtDate(x.published))}<a class="source-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">公式の元情報を開く</a><p class="caution">この画面は公式ページの見出し・説明文を整理したものです。業務判断の前に元情報をご確認ください。</p></div>`;document.getElementById("detail-dialog").showModal()}
function render(){document.querySelectorAll(".tab").forEach(b=>b.setAttribute("aria-selected",String(b.dataset.category===current)));document.getElementById("list-title").textContent=CATEGORIES[current];const rows=allNews.filter(x=>x.category===current);const list=document.getElementById("news-list");list.replaceChildren(...rows.map(x=>card(x)));document.getElementById("result-count").textContent=`${rows.length}件`;document.getElementById("empty").hidden=rows.length!==0}
function buildTabs(){const nav=document.getElementById("tabs");Object.entries(CATEGORIES).forEach(([key,label])=>{const b=document.createElement("button");b.className="tab";b.dataset.category=key;b.textContent=label;b.setAttribute("role","tab");b.addEventListener("click",()=>{current=key;render();document.getElementById("list-title").scrollIntoView({behavior:"smooth",block:"center"})});nav.append(b)})}
async function init(){buildTabs();try{const r=await fetch(`data/news.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json();allNews=data.items||[];document.getElementById("updated").textContent=`${data.updated_label||"更新時刻不明"} 更新`;const important=(data.important_ids||[]).map(id=>allNews.find(x=>x.id===id)).filter(Boolean).slice(0,3);document.getElementById("important-list").replaceChildren(...important.map(x=>card(x,true)));document.getElementById("important-count").textContent=`${important.length}件`;render()}catch{document.getElementById("updated").textContent="更新データを取得できません";document.getElementById("important-list").innerHTML='<div class="empty">現在、ニュースを読み込めません。時間をおいて再度お試しください。</div>';render()}}
document.getElementById("close-detail").addEventListener("click",()=>document.getElementById("detail-dialog").close());document.getElementById("detail-dialog").addEventListener("click",e=>{if(e.target===e.currentTarget)e.currentTarget.close()});init();
